### ISSUE TITLE
This isn't 'real' computed properites

### ISSUE THREAD

**Issue by garygreen** [n7olkachev/laravel-computed-properties#2]
I assume the `computed` name has come from the world of Vue.

Computed properties in Vue react to data that changes on the model, so if you were to update anything in which the computed property used, it will re-compute the computed property.

This is more of a 'watch out' type warning to people thinking it's 'real' computed properties (as they know it) from Vue.

**Comment by n7olkachev** [comment]
Yep, I know, just liked original naming from tweet.
I don't think anyone needs Vue-like computed properties in PHP.

**Comment by garygreen** [comment]
> I don't think anyone needs Vue-like computed properties in PHP

Probably not, but it's worth pointing out because Laravel promotes the use of Vue and has a strong community, so mixing terminology and having different concept behind it is a bit confusing.
