### ISSUE TITLE
Benefit of this package vs simple cacher

### ISSUE THREAD

**Issue by garygreen** [n7olkachev/laravel-computed-properties#3]
How is this package any better than just doing something like the below:

```php
public function getSumAttribute()
{    
    return $this->rememberAs('sum', function() {
        OrderProduct::select(new Expression('sum(price * count)'))
            ->where('order_id', $this->id);
    });
}
```

If you have a basic implementation of `rememberAs` on your model which sees if the key already exists and if not, run the closure and set the value on the model.

**Comment by n7olkachev** [comment]
Please, read this article for better understanding

https://medium.com/@n7olkachev/refactoring-with-computed-properties-package-d78bc594b744

**Comment by garygreen** [comment]
That makes more sense now. I guess I'm totally confused with the whole naming of `computed` because it's not really anything to do with that but instead more of a scope / eloquent thing.
