### ISSUE TITLE
Add to Laravel core

### ISSUE THREAD

**Issue by sebastiaanluca** [n7olkachev/laravel-computed-properties#5]
https://twitter.com/davidgolsen/status/920941756681719809

I wholeheartedly agree as it fits right in and should be a standard feature :) Perhaps create a [laravel/internals](https://github.com/laravel/internals/issues) issue or submit a PR in the hopes it gets accepted faster?

**Comment by n7olkachev** [comment]
Thanks for suggestion! Created https://github.com/laravel/internals/issues/840
