### ISSUE TITLE
Laravel 5.6 still not working

### ISSUE THREAD

**Issue by ASM-Development** [n7olkachev/laravel-computed-properties#6]
>composer require n7olkachev/laravel-computed-properties

Using version ^1.1 for n7olkachev/laravel-computed-properties
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.6.26
    - Conclusion: don't install laravel/framework v5.6.26
    - n7olkachev/laravel-computed-properties v1.1.0 requires illuminate/config ~5.4.0 -> satisfiable by illuminate/config[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - n7olkachev/laravel-computed-properties v1.1.1 requires illuminate/config ~5.4.0|~5.5.0 -> satisfiable by illuminate/config[v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v
5.5.36, v5.5.37, v5.5.39, v5.5.40].
    - don't install illuminate/config v5.4.0|don't install laravel/framework v5.6.26
    - don't install illuminate/config v5.4.13|don't install laravel/framework v5.6.26
    - don't install illuminate/config v5.4.17|don't install laravel/framework v5.6.26
    - don't install illuminate/config v5.4.19|don't install laravel/framework v5.6.26
    - don't install illuminate/config v5.4.27|don't install laravel/framework v5.6.26
    - don't install illuminate/config v5.4.36|don't install laravel/framework v5.6.26
    - don't install illuminate/config v5.4.9|don't install laravel/framework v5.6.26
    - don't install illuminate/config v5.5.0|don't install laravel/framework v5.6.26
    - don't install illuminate/config v5.5.16|don't install laravel/framework v5.6.26
    - don't install illuminate/config v5.5.17|don't install laravel/framework v5.6.26
    - don't install illuminate/config v5.5.2|don't install laravel/framework v5.6.26
    - don't install illuminate/config v5.5.28|don't install laravel/framework v5.6.26
    - don't install illuminate/config v5.5.33|don't install laravel/framework v5.6.26
    - don't install illuminate/config v5.5.34|don't install laravel/framework v5.6.26
    - don't install illuminate/config v5.5.35|don't install laravel/framework v5.6.26
    - don't install illuminate/config v5.5.36|don't install laravel/framework v5.6.26
    - don't install illuminate/config v5.5.37|don't install laravel/framework v5.6.26
    - don't install illuminate/config v5.5.39|don't install laravel/framework v5.6.26
    - don't install illuminate/config v5.5.40|don't install laravel/framework v5.6.26
    - Installation request for laravel/framework (locked at v5.6.26, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.26].
    - Installation request for n7olkachev/laravel-computed-properties ^1.1 -> satisfiable by n7olkachev/laravel-computed-properties[v1.1.0, v1.1.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by n7olkachev** [comment]
Sorry, forgot to make a release:) Now it should be ok
